# Generated by Django 3.2.4 on 2021-06-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=300)),
                ('url', models.TextField(null=True)),
                ('source', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(null=True)),
                ('type', models.IntegerField(null=True)),
            ],
        ),
    ]
