# Generated by Django 3.2.4 on 2021-06-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCovidData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryName', models.CharField(max_length=300)),
                ('newDailyCase', models.IntegerField(null=True)),
                ('newDeathCase', models.IntegerField(null=True)),
                ('newRecoveredCase', models.IntegerField(null=True)),
                ('activeCase', models.IntegerField(null=True)),
                ('criticalCase', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=300)),
                ('currentMarketPrice', models.FloatField(null=True)),
                ('priceChangePoint', models.FloatField(null=True)),
                ('priceChangePercentage', models.FloatField(null=True)),
            ],
        ),
    ]
