# Generated by Django 3.2.4 on 2021-06-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0002_countrycoviddata_indexprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexprice',
            name='priceChangePoint',
        ),
        migrations.AlterField(
            model_name='indexprice',
            name='priceChangePercentage',
            field=models.CharField(max_length=1000),
        ),
    ]
